services:
  db:
    image: postgres:16.2
    container_name: postgres_outlier
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
