name: Tag Version

on:
  push:
    paths-ignore:
      - "src/content/**"
      - "src/lab-modules/**"
      - "public/**"
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    name: Tag New Version
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[release]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: oven-sh/setup-bun@v1
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Tag Version
        run: bun release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
